#!/usr/bin/env python3
"""Post-build optimizer for the mdBook output.

Does three things to the files in `_book/`:
1. Injects <link rel="prefetch"> for every chapter page into every HTML file.
   After any page loads, the browser will prefetch all the other chapters
   during idle time, so sidebar clicks become instant.

2. Injects <link rel="preload"> hints for critical CSS/JS into every page's
   <head>, saving one round-trip on first paint.

3. Writes a service worker (sw.js) and registers it from every HTML page.
   After the first visit, all pages + assets are served from the cache — no
   network round trips at all.

Designed to be safe and idempotent: re-running on the same _book/ is a no-op
if the markers are already present.
"""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

BOOK_DIR = Path(os.environ.get("BOOK_DIR", "_book"))
MARKER = "<!-- optimize-book:injected -->"

PREFETCH_TEMPLATE = '<link rel="prefetch" href="{href}" as="document">'
PRELOAD_TEMPLATE = '<link rel="preload" href="{href}" as="{as_type}"{crossorigin}>'

# Critical resources mdBook always emits. These paths are relative to the
# site root and resolved with each page's own `<base>` or relative-to-root
# heuristic below.
CRITICAL_ASSETS = [
    ("css/general.css", "style"),
    ("css/variables.css", "style"),
    ("css/chrome.css", "style"),
    ("book.js", "script"),
]

SERVICE_WORKER_JS = """// Auto-generated by scripts/optimize-book.py
const CACHE_VERSION = 'skilldesignbook-v1';
const CACHE_SCOPE = self.registration.scope;

// Precache the entire book on install.
// The list is injected below as PRECACHE_URLS.
const PRECACHE_URLS = __PRECACHE_URLS__;

self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_VERSION).then((cache) =>
      cache.addAll(PRECACHE_URLS.map((u) => new Request(u, { cache: 'reload' })))
        .catch(() => {}) // ignore individual asset failures
    )
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_VERSION).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

// Cache-first for same-origin book assets, network-first for others.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET') return;
  if (!url.href.startsWith(CACHE_SCOPE)) return;

  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) {
        // Serve cached version immediately, refresh in background.
        fetch(event.request).then((resp) => {
          if (resp && resp.status === 200 && resp.type === 'basic') {
            caches.open(CACHE_VERSION).then((c) => c.put(event.request, resp));
          }
        }).catch(() => {});
        return cached;
      }
      return fetch(event.request).then((resp) => {
        if (resp && resp.status === 200 && resp.type === 'basic') {
          const copy = resp.clone();
          caches.open(CACHE_VERSION).then((c) => c.put(event.request, copy));
        }
        return resp;
      });
    })
  );
});
"""

SW_REGISTER_SNIPPET = """<script>
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('sw.js', { scope: './' }).catch(() => {});
  });
}
</script>"""


def depth_to_root(html_path: Path, book_root: Path) -> str:
    """Return a relative prefix (e.g. '../') for linking from html_path to
    root. mdBook flattens all pages under _book/ at the same depth, so this
    is usually empty — but we compute it for safety in case of nested folders.
    """
    rel = html_path.parent.relative_to(book_root)
    parts = [p for p in rel.parts if p not in (".", "")]
    if not parts:
        return ""
    return "../" * len(parts)


def collect_pages(book_root: Path) -> list[Path]:
    pages = []
    for p in sorted(book_root.rglob("*.html")):
        # Skip print.html (single-page dump, very heavy, rarely navigated to).
        if p.name in ("print.html", "404.html"):
            continue
        # Skip inside theme/ or other generator-private folders.
        rel_parts = p.relative_to(book_root).parts
        if any(seg.startswith(".") for seg in rel_parts):
            continue
        pages.append(p)
    return pages


def build_prefetch_links(current: Path, pages: list[Path], book_root: Path) -> str:
    links = []
    current_abs = current.resolve()
    for p in pages:
        if p.resolve() == current_abs:
            continue
        rel = os.path.relpath(p, current.parent)
        links.append(PREFETCH_TEMPLATE.format(href=rel))
    return "\n    ".join(links)


def build_preload_links(prefix: str) -> str:
    links = []
    for path, as_type in CRITICAL_ASSETS:
        crossorigin = ""
        if as_type == "font":
            crossorigin = " crossorigin"
        links.append(
            PRELOAD_TEMPLATE.format(
                href=f"{prefix}{path}", as_type=as_type, crossorigin=crossorigin
            )
        )
    return "\n    ".join(links)


def inject_into_html(html: str, prefetch_block: str, preload_block: str) -> str | None:
    if MARKER in html:
        return None  # already injected, idempotent no-op

    head_close = html.find("</head>")
    if head_close == -1:
        return None  # malformed, skip

    injection = (
        f"\n    {MARKER}\n"
        f"    {preload_block}\n"
        f"    {prefetch_block}\n"
        f"    {SW_REGISTER_SNIPPET}\n"
    )
    return html[:head_close] + injection + html[head_close:]


def generate_service_worker(book_root: Path, pages: list[Path]) -> None:
    precache = []
    # Cache root pages.
    for p in pages:
        rel = p.relative_to(book_root).as_posix()
        precache.append(f"./{rel}")
    # Cache critical assets.
    for path, _ in CRITICAL_ASSETS:
        precache.append(f"./{path}")
    # Also cache a handful of mdBook-generated assets if present.
    extras = [
        "highlight.css",
        "tomorrow-night.css",
        "ayu-highlight.css",
        "favicon.svg",
        "favicon.png",
        "searchindex.json",
        "searchindex.js",
        "searcher.js",
        "clipboard.min.js",
        "elasticlunr.min.js",
        "mark.min.js",
    ]
    for extra in extras:
        if (book_root / extra).exists():
            precache.append(f"./{extra}")

    precache_urls_literal = "[" + ", ".join(f'"{u}"' for u in precache) + "]"
    sw_content = SERVICE_WORKER_JS.replace("__PRECACHE_URLS__", precache_urls_literal)
    (book_root / "sw.js").write_text(sw_content, encoding="utf-8")


def main() -> int:
    if not BOOK_DIR.exists():
        print(f"error: {BOOK_DIR} does not exist — run `mdbook build` first", file=sys.stderr)
        return 1

    pages = collect_pages(BOOK_DIR)
    if not pages:
        print("error: no HTML pages found in _book/", file=sys.stderr)
        return 1

    print(f"optimize-book: {len(pages)} pages found in {BOOK_DIR}/")

    modified = 0
    skipped = 0
    for page in pages:
        html = page.read_text(encoding="utf-8")
        prefix = depth_to_root(page, BOOK_DIR)
        prefetch_block = build_prefetch_links(page, pages, BOOK_DIR)
        preload_block = build_preload_links(prefix)
        new_html = inject_into_html(html, prefetch_block, preload_block)
        if new_html is None:
            skipped += 1
            continue
        page.write_text(new_html, encoding="utf-8")
        modified += 1

    generate_service_worker(BOOK_DIR, pages)
    sw_kb = (BOOK_DIR / "sw.js").stat().st_size / 1024

    print(f"optimize-book: injected into {modified} pages (skipped {skipped})")
    print(f"optimize-book: wrote sw.js ({sw_kb:.1f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
